languageCode = "en"
languageName = "English"
weight = 1
title = "kmarble.dev"

[params]
  description = ""

[author]
  name = "Key"
  image = ""
  headline = ""
  bio = ""
  links = [
    { email = "mailto:admin@kmarble.dev" },
    { github = "https://github.com/kdmarble" },
  ]
