colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]
disableImageOptimization = false
disableTextInHeader = false

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  homepageImage = ""
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = false
  layoutBackgroundBlur = false

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showComments = true
  sharingLinks = ["mastodon", "linkedin", "email"]

[list]
  showHero = false
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = false
  groupByYear = true

[taxonomy]
  showTermCount = true

[umami]
  websiteid = "e799341b-22d9-4957-abb7-9d68229b9201"
  domain = "analytics.stinkiejet.club"
